// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/ffceea9dd124d277c4597c7bd12930666ec074c5/vinyl-source-stream/vinyl-source-stream.d.ts
declare module "vinyl-source-stream" {
    function vinylSourceStream(filename: string): NodeJS.ReadWriteStream;
    export = vinylSourceStream;
}